### ISSUE TITLE
它有可能支持代码库的上传吗？以及它和QAnything有什么区别

### ISSUE THREAD

**Issue by CoderYiFei** [ArtisanCloud/BrainX#2]

**Comment by Matrix-X** [comment]
抱歉，才看到这个提问，作为rag系统，市面上好多同质化的功能，首先这个项目主要底层就是langgraph的封装，包括后续可以支持llamaindex。其次现阶段我们是满足自己2b业务在做开发。也希望有一些企业的应用来增强这个开源项目。最后是我们定位是想把我们brainx和powerx打通。这块是我们的方向

**Comment by Matrix-X** [comment]
代码库上传应该会在workflow里体现
